using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace LuaSTG.Generators
{
    [Generator]
    public class LuaBindGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var methodDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => s is MethodDeclarationSyntax m && m.AttributeLists.Count > 0,
                    transform: static (ctx, _) =>
                    {
                        var methodDecl = (MethodDeclarationSyntax)ctx.Node;
                        foreach (var attributeList in methodDecl.AttributeLists)
                        {
                            foreach (var attribute in attributeList.Attributes)
                            {
                                string attrName = attribute.Name.ToString();
                                if (attrName == "LuaBind" || attrName == "LuaBindAttribute" || attrName.EndsWith(".LuaBind"))
                                {
                                    return methodDecl;
                                }
                            }
                        }
                        return null;
                    })
                .Where(static m => m is not null);

            context.RegisterSourceOutput(methodDeclarations.Collect(), Execute);
        }

        private static void Execute(SourceProductionContext context, System.Collections.Immutable.ImmutableArray<MethodDeclarationSyntax?> methods)
        {
            if (methods.IsEmpty) return;

            var grouped = methods.Where(m => m != null)
                .GroupBy(m => m!.Parent as ClassDeclarationSyntax)
                .Where(g => g.Key != null);

            foreach (var group in grouped)
            {
                var classDecl = group.Key!;
                string className = classDecl.Identifier.Text;

                var namespaceDecl = classDecl.Ancestors().OfType<BaseNamespaceDeclarationSyntax>().FirstOrDefault();
                string namespaceName = namespaceDecl != null ? namespaceDecl.Name.ToString() : "Global";

                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated />");
                sb.AppendLine("using System.Runtime.CompilerServices;");
                sb.AppendLine("using System.Runtime.InteropServices;");
                sb.AppendLine($"namespace {namespaceName};");
                sb.AppendLine();
                sb.AppendLine($"public unsafe partial class {className}");
                sb.AppendLine("{");
                sb.AppendLine("    public static unsafe partial class CFunctions");
                sb.AppendLine("    {");

                foreach (var method in group)
                {
                    string methodName = method!.Identifier.Text;

                    sb.AppendLine("        [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvCdecl) })]");
                    sb.AppendLine($"        private static int __Native_{methodName}(luajit_sharp.LuaState L)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            return {className}.{methodName}(L);");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                    sb.AppendLine($"        public static lua_CFunction {methodName}");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            get => (lua_CFunction)(delegate* unmanaged[Cdecl]<luajit_sharp.LuaState, int>)&__Native_{methodName};");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                }

                sb.AppendLine("    }");
                sb.AppendLine("}");

                context.AddSource($"{className}_LuaBinds.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            }
        }
    }
}